version: '3.5'
services:
  db:
    build: mysql
    image: users_mysql:1.0.0
    ports: 
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: Grisha11234
    volumes:
      - /docker-entrypoint-initdb.d
    networks:
      - users_ntwrk

  it_academy_users:
    build: it_academy_users
    image: it_academy_users:1.0.0
    ports:
      - 80:8080
    restart: always
    networks:
      - users_ntwrk

networks:
  users_ntwrk:
    name: users_ntwrk