version: '3.5'
services:
  db:
    build: mysql
    image: consumers_mysql:1.0.0
    ports: 
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE: consumers
      MYSQL_ROOT_PASSWORD: Grisha11234
    volumes:
      - /docker-entrypoint-initdb.d
    networks:
      - consumers_ntwrk

  consumers_demo:
    build: consumers_demo
    image: consumers_demo:1.0.0
    ports:
      - 80:8080
    restart: always
    networks:
      - consumers_ntwrk

networks:
  consumers_ntwrk:
    name: consumers_ntwrk